In [1]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# 임의의 단어 벡터
word1 = np.array([[1, 2, 3]])
word2 = np.array([[2, 3, 4]])

# 코사인 유사도 계산
similarity = cosine_similarity(word1, word2)
print("코사인 유사도:", similarity[0][0])

코사인 유사도: 0.9925833339709303


In [2]:
similarity

array([[0.99258333]])

## 자연어 임베딩(Embedding)이란?

자연어 임베딩은 **텍스트(단어/문장/문서)를 고정 길이의 실수 벡터(vector)로 바꾸는 표현 방식**이다.  
즉, 컴퓨터가 다룰 수 있도록 **문자를 수치화**하되, 단순 ID가 아니라 **의미·문맥·문법적 특징**이 벡터 공간에 반영되도록 만든다.

- 임베딩 덕분에 텍스트끼리 **유사도(코사인 유사도 등)**를 계산할 수 있고  
- 머신러닝/딥러닝 모델에 **입력 피처**로 넣을 수 있으며  
- “king - man + woman ≈ queen” 같은 **의미 연산**이 벡터 공간에서 가능해진다.

---

## 임베딩 핵심 정리 표

| 구분 | 내용 | 예시/포인트 |
|---|---|---|
| 정의 | 텍스트를 **고정 길이 실수 벡터**로 변환 | 단어/문장/문서 → `R^d` 벡터 |
| 목적 | 컴퓨터가 텍스트를 수치로 처리 + 의미를 보존 | 단순 라벨 인코딩과 다름 |
| 표현 대상 | 단어 임베딩 / 문장 임베딩 / 문서 임베딩 | word2vec(단어), SBERT(문장) |
| 벡터 의미 | 벡터 공간에서 **거리/각도**가 의미적 유사성을 반영 | 가까울수록 의미가 비슷한 경향 |
| 대표 유사도 지표 | 코사인 유사도, 유클리드 거리 | 코사인: 방향(의미) 중심 비교 |
| 장점 | 의미적 관계 수치화, 모델 입력 가능, 일반화에 유리 | 검색/추천/분류/클러스터링 등 |
| 한계 | 데이터·학습 방식에 따라 편향/품질 차이, OOV 문제 | 학습 코퍼스에 없는 단어 처리 |
| 활용 | 분류, 검색, 추천, 군집화, QA, RAG 등 | query↔doc 유사도 계산 |
| 학습 방식(큰 분류) | 정적(Static) vs 문맥(Contextual) | 정적: word2vec / 문맥: BERT 계열 |
| 정적 임베딩 특징 | 단어당 벡터 1개(문맥 변화 반영 어려움) | “bank” (강둑/은행) 구분 약함 |
| 문맥 임베딩 특징 | 같은 단어라도 문맥에 따라 벡터가 달라짐 | “bank”가 문장에 따라 의미 분리 |

## 04-02. 벡터화(Vectorization) 정리

### 벡터화란?
벡터화는 텍스트/이미지/오디오 같은 **비정형 데이터를 고정된 차원의 수치 벡터로 변환**하는 과정이다.  
모델이 처리할 수 있도록 **수치화**하며, 연산 최적화와 유사도 계산을 가능하게 한다.
## 04-02-01. 벡터화 개요 표

| 항목 | 내용 | 핵심 포인트 |
|---|---|---|
| 정의 | 데이터를 **고정 차원 벡터**로 변환 | 비정형 → 수치화 |
| 목적 | ML/DL 모델 입력 가능, 연산 최적화, 유사도 계산 | 거리/유사도 기반 비교 가능 |
| 필요성 | 모델은 숫자만 입력으로 받음 | 텍스트/이미지/오디오를 숫자로 변환 |
| 장점 | 수학적 연산 가능 → 패턴 분석/예측 학습에 적합 | 학습/추론 가능해짐 |
| 성능 영향 | 벡터화 방식에 따라 성능 차이가 큼 | 태스크/데이터에 맞춰 선택 필요 |
| 종류(큰 분류) | 수동 벡터화 vs 자동 벡터화 | Feature Engineering vs 딥러닝 |

## 벡터화 종류 표 (수동 vs 자동)

| 구분 | 수동 벡터화(Feature Engineering) | 자동 벡터화(딥러닝 기반) |
|---|---|---|
| 특징 | 사람이 특징을 정의해 수치화 | 모델이 데이터에서 특징을 학습해 벡터화 |
| 장점 | 해석 용이, 단순 모델과 궁합 좋음 | 표현력 높음, 복잡한 패턴 학습 가능 |
| 단점 | 특징 설계가 어렵고 한계가 있음 | 데이터/연산 자원 필요, 해석이 어려울 수 있음 |
| 예시 | BoW, TF-IDF, 수작업 특징(길이, 빈도 등) | Word Embedding, BERT 임베딩, CNN 특징 벡터 등 |

## 04-02-02. 적용 분야 표

| 분야 | 벡터화 대상 | 활용 예시 |
|---|---|---|
| NLP(자연어 처리) | 문장/문서/단어 | 감성 분석, 문서 분류, 번역 |
| 컴퓨터 비전 | 이미지(픽셀/특징) | 객체 인식, 분류, 탐지 |
| 추천 시스템 | 사용자/아이템 | 유사도 기반 추천, 랭킹 모델 |

## 04-02-03. 벡터화 한계 표

| 한계 | 설명 | 영향 |
|---|---|---|
| 차원의 저주 | 고차원 벡터는 계산 비용 증가 | 학습/유사도 계산 느려짐 |
| 정보 손실 | 부적절한 방식 선택 시 중요한 정보 누락 | 성능 저하 가능 |
| 범용성 부족 | 한 방법이 모든 문제에 최적은 아님 | 데이터/목표에 맞춘 선택 필요 |

In [3]:
from konlpy.tag import Okt

# 텍스트 데이터
text = "자연어 처리는 재미있다."

# 형태소 분석
okt = Okt()
morphs = okt.morphs(text)
print("형태소 분석 결과:", morphs)

형태소 분석 결과: ['자연어', '처리', '는', '재미있다', '.']


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# 문장 데이터
corpus = ["자연어 처리는 재미있다.", "Python으로 가능하다."]

# BoW 벡터화
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)            # 단어 사전 학습 + BoW (빈도) 희소행렬 벡터로 변환

print("BoW 벡터화 결과:\\n", X.toarray())          # 희소행렬을 밀집 배열 형태로 출력 
print("단어 사전:", vectorizer.vocabulary_)       # {단어 : 인덱스} 형태의 단어사전

BoW 벡터화 결과:\n [[0 0 1 1 1]
 [1 1 0 0 0]]
단어 사전: {'자연어': 2, '처리는': 4, '재미있다': 3, 'python으로': 0, '가능하다': 1}


In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 문장 데이터
corpus = ["Python으로 자연어 처리는 재미있다.", "Python으로 가능하다."]

# TF-IDF 벡터화
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)        # IDF 학습(fit) + TF-IDF 벡터 변환 -> 희소행렬

print("TF-IDF 결과:\\n", X.toarray())        # 희소행렬 -> 밀집 배열 형태로 변환
print("단어 사전:", vectorizer.vocabulary_)   # {단어 : 인덱스} 형태의 단어사전

TF-IDF 결과:\n [[0.37997836 0.         0.53404633 0.53404633 0.53404633]
 [0.57973867 0.81480247 0.         0.         0.        ]]
단어 사전: {'python으로': 0, '자연어': 2, '처리는': 4, '재미있다': 3, '가능하다': 1}



## CBOW vs Skip-gram 비교 표

| 구분 | CBOW (Continuous Bag of Words) | Skip-gram |
|---|---|---|
| 핵심 아이디어 | **주변 단어들(Context)**로 **중심 단어(Target)**를 맞춤 | **중심 단어(Target)**로 **주변 단어들(Context)**을 맞춤 |
| 예측 방향 | (주변) → (중심) | (중심) → (주변) |
| 입력(Input) | 주변 단어 벡터들(여러 개) | 중심 단어 벡터(1개) |
| 출력(Output) | 중심 단어 확률 | 주변 단어 확률(여러 개) |
| 강점 | 학습이 비교적 빠르고 안정적 | 희귀 단어(드문 단어) 표현을 더 잘 학습하는 경향 |
| 약점 | 희귀 단어에 약할 수 있음 | 학습이 느리고 계산량이 더 큰 편 |
| 잘 맞는 상황 | 데이터가 크고, 빠르게 임베딩을 만들고 싶을 때 | 희귀 단어 의미까지 잘 살리고 싶을 때 |
| 직관적 비유 | “주변 문맥을 보고 빈칸 단어 맞히기” | “주어진 단어로 주변에 뭐가 나올지 예측하기” |


## 아주 짧은 예시(직관)
- 문장: “나는 **아침에** 커피를 마신다”
  - **CBOW**: (나는, 커피를, 마신다) → **아침에** 예측
  - **Skip-gram**: **아침에** → (나는, 커피를, 마신다) 예측

In [ ]:
from gensim.models import Word2Vec # 단어 임베딩 학습 모델 

# 샘플 문장
sentences = [["자연어", "처리", "재미있다"], ["Python", "가능하다"]]

# Word2Vec 모델 학습
model = Word2Vec(
    sentences,          # 학습에 사용할 토큰화 문장들
    vector_size=100,    # 단어 벡터 차원 수
    window=3,           # 주변 문맥으로 볼 단어 범위 (좌우 3개)
    min_count=1,        # 최소 등장 횟수 1개 
    sg=0                # 0 = CBOW (주변 -> 중심 단어 예측), 1 = Skip-gram(중심 -> 주변 단어 예측)
)

# 단어 벡터 확인
print("단어 '자연어'의 벡터:", model.wv["자연어"])  # 학습된 '자연어'의 임베딩 벡터

단어 '자연어'의 벡터: [-0.00713902  0.00124103 -0.00717672 -0.00224462  0.0037193   0.00583312
  0.00119818  0.00210273 -0.00411039  0.00722533 -0.00630704  0.00464722
 -0.00821997  0.00203647 -0.00497705 -0.00424769 -0.00310898  0.00565521
  0.0057984  -0.00497465  0.00077333 -0.00849578  0.00780981  0.00925729
 -0.00274233  0.00080022  0.00074665  0.00547788 -0.00860608  0.00058446
  0.00686942  0.00223159  0.00112468 -0.00932216  0.00848237 -0.00626413
 -0.00299237  0.00349379 -0.00077263  0.00141129  0.00178199 -0.0068289
 -0.00972481  0.00904058  0.00619805 -0.00691293  0.00340348  0.00020606
  0.00475375 -0.00711994  0.00402695  0.00434743  0.00995737 -0.00447374
 -0.00138926 -0.00731732 -0.00969783 -0.00908026 -0.00102275 -0.00650329
  0.00484973 -0.00616403  0.00251919  0.00073944 -0.00339215 -0.00097922
  0.00997913  0.00914589 -0.00446183  0.00908303 -0.00564176  0.00593092
 -0.00309722  0.00343175  0.00301723  0.00690046 -0.00237388  0.00877504
  0.00758943 -0.00954765 -0.00800821 -

In [10]:
model.wv.similarity("자연어","재미있다")

np.float32(0.17018886)

In [11]:
model.wv.most_similar("자연어",topn = 5)

[('재미있다', 0.17018885910511017),
 ('Python', 0.004503019154071808),
 ('가능하다', -0.027750344946980476),
 ('처리', -0.04461710527539253)]

In [12]:
import gensim.downloader as api

# 1) 미리 학습된 GloVe 로드 (처음 1번은 다운로드 시간이 걸림)
# 50차원 버전: 가볍고 실습용으로 좋음
glove = api.load("glove-wiki-gigaword-50")

# 2) 단어 벡터 확인 (길이=50)
print("king 벡터 차원:", glove["king"].shape)

# 3) 코사인 유사도
print("similarity(king, queen):", glove.similarity("king", "queen"))
print("similarity(king, banana):", glove.similarity("king", "banana"))

# 4) 가장 비슷한 단어 top-n
print("most_similar('king'):", glove.most_similar("king", topn=5))

# 5) 벡터 연산(관계) 예시: king - man + woman ≈ queen
print(glove.most_similar(positive=["king", "woman"], negative=["man"], topn=5))

[==================================================] 100.0% 66.0/66.0MB downloaded
king 벡터 차원: (50,)
similarity(king, queen): 0.7839044
similarity(king, banana): 0.22074081
most_similar('king'): [('prince', 0.8236179351806641), ('queen', 0.7839043140411377), ('ii', 0.7746229767799377), ('emperor', 0.7736247777938843), ('son', 0.766719400882721)]
[('queen', 0.8523604273796082), ('throne', 0.7664334177970886), ('prince', 0.7592144012451172), ('daughter', 0.7473883628845215), ('elizabeth', 0.7460220456123352)]


In [ ]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

# 1) 예시 문서(문장) 준비
docs = [
    "자연어 처리는 재미있다",
    "파이썬으로 자연어 처리를 할 수 있다",
    "축구 경기는 정말 재미있다",
    "오늘 날씨가 좋다"
]

# 2) Doc2Vec은 문서마다 태그(아이디)가 필요함
tagged_docs = [
    TaggedDocument(words=d.split(), tags=[f"DOC_{i}"])
    for i, d in enumerate(docs)
]   # 각 문서를 (토큰리스트, 문서 ID)로 변환

# 3) Doc2Vec 모델 학습
model = Doc2Vec(
    documents=tagged_docs,  # 태그가 붙은 문서들로 학습
    vector_size=50,   # 문서 벡터 차원
    window=3,         # 문맥 범위
    min_count=1,      # 최소 등장 횟수
    workers=2,        # 병열 처리 CPU 쓰레드 갯수
    epochs=50         # 학습 반복
)

# 4) 학습된 문서 벡터 확인
print("DOC_0 벡터 일부:", model.dv["DOC_0"][:10])

# 5) 특정 문서와 가장 유사한 문서 찾기
print("\nDOC_0와 유사한 문서:")
print(model.dv.most_similar("DOC_0", topn=3))

# 6) 새 문장(학습에 없던 문장)도 벡터로 추정 가능(infer_vector)
new_doc = "자연어 처리는 파이썬으로 가능하다"
new_vec = model.infer_vector(new_doc.split())

print("\n새 문장과 유사한 문서:")
print(model.dv.most_similar([new_vec], topn=3))

DOC_0 벡터 일부: [-0.01058207 -0.01189603 -0.01985634  0.01694183  0.00701691  0.00072557
 -0.01981407 -0.01017613 -0.01967002  0.00412226]

DOC_0와 유사한 문서:
[('DOC_1', 0.2878270745277405), ('DOC_2', 0.1307842880487442), ('DOC_3', -0.07168305665254593)]

새 문장과 유사한 문서:
[('DOC_0', -0.04926169663667679), ('DOC_1', -0.0635066106915474), ('DOC_3', -0.17218726873397827)]


In [14]:
from sklearn.decomposition import LatentDirichletAllocation     # LDA
from sklearn.feature_extraction.text import CountVectorizer     # 문서의 단어 등장 횟수 (BoW)로 변환하는 벡터라이저

# 문장 데이터
corpus = ["자연어 처리는 재미있다.", "Python으로 가능하다."]

# BoW 벡터화
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)    # 단어 사전 학습 + 문서-단어 희소행렬 변환

# LDA 모델 학습
lda = LatentDirichletAllocation(
    n_components=2,     # 찾을 주제 갯수
    random_state=0      # 재현성 (시드 고정)
)
lda.fit(X)      # BoW 행렬로 LDA 모델 학습(주제 - 단어 분포/문서-주제 분포 추정)

# 주제별 단어 분포
print("주제별 단어 분포:\\n", lda.components_)  # 각 주제에서 단어가 얼마나 중요한지(가중치)

주제별 단어 분포:\n [[1.4913572  1.4913572  0.50945773 0.50945773 0.50945773]
 [0.5086428  0.5086428  1.49054227 1.49054227 1.49054227]]


In [ ]:
feature_names = vectorizer.get_feature_names_out()  # 단어 사전에서 이름

for topic_idx, topic in enumerate(lda.components_):
    top_idx = topic.argsort()[::-1][:5]     # 가중치가 가장 큰 단어 인덱스 TOP5 추출 (오름차순 정렬 후 역순)
    print(f"Topic {topic_idx}: ", [(feature_names[i], topic[i]) for i in top_idx]) # (단어, 가중치) 형태로 TOP5출력

Topic 0:  [('python으로', np.float64(1.4913571964571597)), ('가능하다', np.float64(1.491357196456652)), ('자연어', np.float64(0.5094577321201083)), ('처리는', np.float64(0.5094577321189349)), ('재미있다', np.float64(0.5094577321184829))]
Topic 1:  [('재미있다', np.float64(1.4905422678815157)), ('처리는', np.float64(1.4905422678810638)), ('자연어', np.float64(1.4905422678798905)), ('가능하다', np.float64(0.5086428035433468)), ('python으로', np.float64(0.5086428035428391))]


In [18]:
from gensim.models import FastText # 서브워드 (n-그램) 기반 단어 임베딩 모델

# 토큰화된 문장 준비
sentences =[
    ["자연어", "처리는", "재미있다"],
    ["파이썬", "으로", "자연어", "처리","가능하다"],
    ["자연어", "처리", "공부","하자"]
]
# FastText : 단어를 '문자 n-그램(서브워드)' 조합으로도 표현하여 OOV(미등장 단어) 벡터 생성에 강함
model = FastText(
    sentences,          # 학습 데이터
    vector_size = 50,   # 단어 벡터 차원 수
    window = 3,         # 주변 문맥 범위 (좌우 3개씩)
    min_count = 1 ,     # 최소 등장 횟수(1번 이상일때 사용)
    sg = 1,             # 0 = CBOW (주변 -> 중심 단어 예측), 1= Skip-gram(중심 -> 주변 단어 예측)
    min_n = 2,          # 서브워드 (문자 n-gram) 최소 길이
    max_n = 5,          # 서브워드 (문자 n-gram) 최대 길이
    epochs = 50         # 학습 반복 횟수
)

# 단어 벡터 확인 ('자연어') 임베딩 벡터 중 앞 10개 차원
print('자연어 벡터 일부 :',model.wv['자연어'][:10])

# 유사 단어 : 코사인 유사도가 높은 단어 TOP3
print('자연어와 비슷한 단어 :', model.wv.most_similar("자연어",topn = 3 ))

# 단어 간 코사인 유사도 확인 
print("similarity(자연어, 처리) :", model.wv.similarity("자연어", "처리"))


자연어 벡터 일부 : [ 0.00364446 -0.00144183 -0.00430582  0.00206623 -0.00079104 -0.00219508
 -0.00202816  0.00041452  0.00483354 -0.00515762]
자연어와 비슷한 단어 : [('파이썬', 0.04029621556401253), ('처리는', 0.0400528647005558), ('처리', 0.02612016536295414)]
similarity(자연어, 처리) : 0.02612016
